from .create_sensors_records_by_csv_file import CreateSensorsRecordsByCsvFile
from .create_sensors_record_by_api import CreateSensorsRecordByApi
from .create_sensors_records_by_form import CreateSensorsRecordByForm
from .get_sensors_dashboard_page_data import GetSensorDashboardPageData
from .get_last_sensors_record_page_data import GetLastSensorsRecordPageData
from .get_sensors_records_table_page_data import GetSensorsRecordsTablePageData
from .update_sensors_records import UpdateSensorsRecord
from .delete_sensors_records import DeleteSensorsRecord

create_sensors_records_by_csv_file = CreateSensorsRecordsByCsvFile()
create_sensors_record_by_api = CreateSensorsRecordByApi()
create_sensors_records_by_form = CreateSensorsRecordByForm()
get_sensors_dashboard_page_data = GetSensorDashboardPageData()
get_last_sensors_record_page_data = GetLastSensorsRecordPageData()
get_sensors_records_table_page_data = GetSensorsRecordsTablePageData()
update_sensors_records = UpdateSensorsRecord()
delete_sensors_records = DeleteSensorsRecord()
