services:
  mysql:
    image: mysql:8
    container_name: smart-farming-database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_USER: ${MYSQL_DATABASE_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD}
            --silent",
        ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s

  app:
    build: .
    container_name: smart-farming-app
    environment:
      SECRET_KEY: ${SECRET_KEY}
      URL: ${URL}
      MYSQL_DATABASE_HOST: database
      MYSQL_DATABASE_USER: ${MYSQL_DATABASE_USER}
      MYSQL_DATABASE_NAME: ${MYSQL_DATABASE_NAME}
      MYSQL_DATABASE_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      GOOGLE_DRIVE_DATABASE_BACKUP_FOLDER_ID: ${GOOGLE_DRIVE_DATABASE_BACKUP_FOLDER_ID}
      SUPPORT_EMAIL_APP_PASSWORD: ${SUPPORT_EMAIL_APP_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
