CSV_FILE_COLUMNS = {
    "sensors_records": [
        "data",
        "hora",
        "dia da semana",
        "umidade Ambiente",
        "umidade solo",
        "temperatura",
        "volume de Água (ml)",
        "planta",
    ],
    "checklist_records": [
        "em qual plantio você quer coletar os dados?",
        "data da coleta",
        "hora da coleta (inserir valor de 0 a 23)",
        "umidade do solo?",
        "ph do solo?",
        "temperatura ambiente?",
        "validade da adubação?",
        "consumo de água (mililitros)?",
        "umidade do ar?",
        "luminosidade (lux)?",
        "iaf (índice de área foliar)?",
        "qual o aspecto das folhas?",
        "qual a coloração das folhas?",
        "algum desvio detectado durante o processo?",
        "planta",
    ],
}
