from .checklist_records_repository import CheckListRecordsRepository
from .sensors_records_repository import SensorRecordsRepository
from .plants_records_repository import PlantsRecordsRepository

checklist_records_repository = CheckListRecordsRepository()
sensors_records_repository = SensorRecordsRepository()
plants_records_repository = PlantsRecordsRepository()