from .checklist_records_repository import CheckListRecordsRepository
from .sensors_records_repository import SensorRecordsRepository

checklist_records_repository = CheckListRecordsRepository()
sensors_records_repository = SensorRecordsRepository()
