"""empty message

Revision ID: 1f446952b9f2
Revises: 6f4f74f63f4f
Create Date: 2026-02-08 16:41:37.778031

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '1f446952b9f2'
down_revision = '6f4f74f63f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###
