"""empty message

Revision ID: 4536d65ca6ab
Revises: 1f446952b9f2
Create Date: 2026-02-08 16:43:25.075423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = '4536d65ca6ab'
down_revision = '1f446952b9f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
