from abc import ABC

from core.entities import Plant


class PlantsRepositoryInterface(ABC):
    def create_plant(self, plants_record: Plant) -> Plant: ...
    def get_plants(self) -> list[Plant]: ...
    def get_plant_by_id(self, id: str) -> Plant | None: ...
    def get_plant_by_name(self, name: str) -> Plant | None: ...
    def get_last_plant(self) -> Plant | None: ...
    def filter_plants_by_name(self, plant_name: str) -> list[Plant]: ...
    def update_plant_by_id(self, plant: Plant) -> None: ...
    def delete_plant_by_id(self, id: str) -> None: ...
