from abc import ABC

from core.entities import User


class UsersRepositoryInterface(ABC):
    def get_user_by_id(
        self, id: str, should_include_password: bool = False
    ) -> User | None: ...
    def get_user_by_email(self, email: str) -> User | None: ...
    def get_user_active_plant_id(self, email: str) -> User | None: ...
    def update_password(self, email, new_password: str) -> None: ...
    def update_active_plant(self, id: str, plant_id: str) -> None: ...
