name: Continuous Delivery

on:
  push:
    tags:
      - '*'

jobs:
  CD:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app
        uses: actions/checkout@v4

      - name: Deploy app
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          source: "."
          target: "~/smart-farming-scp"

      - name: Run app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd ~/smart-farming-scp
            echo ${{ secrets.ENV_FILE }}
            env_file_string=$(echo "${{ secrets.ENV_FILE }}")
            echo $env_file_string | tr ' ' '\n' | sed 's/\([^=]\+\)=\([^ ]\+\)/\1=\2/' > ~/smart-farming-scp/.env
            docker compose up -d
